# Generated by Django 5.2.5 on 2025-10-04 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('provider_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=150)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('email_id', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('category_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.servicecategory')),
            ],
        ),
    ]
