# Generated by Django 5.2.5 on 2025-10-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='end_hours',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='start_hours',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
