# Generated by Django 5.2.5 on 2025-10-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_serviceprovider_end_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='profile_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
