# Generated by Django 5.2.5 on 2025-10-10 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
        ('users', '0002_serviceprovider_end_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerschedule',
            old_name='service_id',
            new_name='service',
        ),
        migrations.AddField(
            model_name='providerschedule',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.serviceprovider'),
        ),
    ]
