# Generated by Django 5.2.5 on 2025-10-14 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='appointment_datetime',
            new_name='app_start_time',
        ),
        migrations.AddField(
            model_name='appointments',
            name='app_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
