# Generated by Django 5.2.5 on 2025-10-27 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_rename_appointment_datetime_appointments_app_start_time_and_more'),
        ('users', '0004_serviceprovider_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='users.serviceprovider'),
        ),
    ]
