# Generated by Django 5.2.5 on 2025-10-26 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='recipient_provider',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='recipient_customer',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='notification_ID',
        ),
        migrations.AddField(
            model_name='notifications',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='title',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
